#!/usr/bin/env bash

## Files and cmd
FILE="$HOME/.cache/eww_launch.dashboard"
CFG="$HOME/.config/eww/dashboard"
EWW=$(which eww)
#B_WIDTH=$(hyprctl monitors | grep "@" | awk 'NR==1{print $1}' | sed 's/.*x\([0-9]*\)@.*/\1\*0.25/' | bc | awk -F. '{print $1x}')
#B_HEIGHT=$(hyprctl monitors | grep "@" | awk 'NR==1{print $1}' | sed 's/\([0-9]*\)x.*/\1/')
#echo "$B_HEIGHT"
#echo "$B_WIDTH"

## Run eww daemon if not running already
if [[ ! $(pidof eww) ]]; then
	${EWW} daemon
	sleep 1
fi

## Open widgets
run_eww() {
	${EWW} --config "$CFG" open-many \
		background clock menu
}

## Launch or close widgets accordingly
if [[ ! -f "$FILE" ]]; then
	touch "$FILE"
	run_eww
else
	${EWW} --config "$CFG" close \
		background clock menu
	rm "$FILE"
fi
